# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildarm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: Jellyfin.SkiaSharp.NativeAssets.LinuxArm/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu, Jellyfin.SkiaSharp.NativeAssets.LinuxArm/depot_tools, Jellyfin.SkiaSharp.NativeAssets.LinuxArm/tools 
        # An explicit key for restoring and saving the cache
        key: cachebuild

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: cd Jellyfin.SkiaSharp.NativeAssets.LinuxArm && bash cross-compile-libSkiaSharp.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: Jellyfin.SkiaSharp.NativeAssets.LinuxArm/skia/out/
      
  buildmusl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: cd Jellyfin.SkiaSharp.NativeAssets.LinuxMusl && bash compile-libSkiaSharp.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: Jellyfin.SkiaSharp.NativeAssets.LinuxMusl/skia/out/
